### ISSUE TITLE
Lab Report1 Feedback

### ISSUE THREAD

**Issue by MohaElder** [akshatja1n/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
    - Did not count keystrokes
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

Great job! Just include the keystroke count and you are all set!
--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by akshatja1n** [comment]
I submitted a regrade request with the following text:

**Comment by akshatja1n** [comment]
I submitted a regrade request on Gradescope with the following text.

I have added the keystrokes in the last section.

https://github.com/akshatja1n/cse15l-lab-reports/issues/1
https://akshatja1n.github.io/cse15l-lab-reports/lab-report-1-week-2.html

**Comment by MohaElder** [comment]
Good job! Already graded.
